### ISSUE TITLE
(1.20.1) Game crashed when waking up from bed

### ISSUE THREAD

**Issue by jojofenin99** [MrMorgan0/SSA-1.20.1#2] opened 2023-09-28 03:38 UTC
**Describe the bug**
The bug seems to be the game calling something from the ssa mod but then it crashes
here are the crash and normal logs:
[crash-2023-09-27_23.35.09-client.txt](https://github.com/MrMorgan0/SSA-1.20.1/files/12745259/crash-2023-09-27_23.35.09-client.txt)
[latest.log](https://github.com/MrMorgan0/SSA-1.20.1/files/12745261/latest.log)

**Comment by MrMorgan0** [comment] 2023-10-05 10:10
I figured out, that the issue is only with forge 47.2.0 version. But I can't get the same crash, so I'll do some manipulations with object registration code and I hope I can fix that issue. Check available updates via minecraft mods menu.

**Comment by MrMorgan0** [comment] 2023-10-05 18:30
Fixed in version 0.4

**Closed by MrMorgan0** 2023-10-05 18:30 UTC
Labels: bug, duplicate, enhancement, help wanted, question

**Comment by jojofenin99** [comment] 2023-10-05 19:58
thx
